"""empty message

Revision ID: 063427f8bb2b
Revises: 8df0b660e0ce
Create Date: 2017-08-24 19:24:15.956544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063427f8bb2b'
down_revision = '8df0b660e0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('List_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_price_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_price_key', 'items', ['price'])
    op.drop_column('items', 'List_id')
    # ### end Alembic commands ###
