"""empty message

Revision ID: a10241b60c41
Revises: 063427f8bb2b
Create Date: 2017-10-11 08:53:57.435008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a10241b60c41'
down_revision = '063427f8bb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    op.create_foreign_key(None, 'items', 'shopping_lists', ['List_id'], ['id'])
    op.add_column('shopping_lists', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('shopping_lists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shopping_lists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.drop_column('shopping_lists', 'user_id')
    op.drop_column('shopping_lists', 'due_date')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_table('todos',
    sa.Column('todo_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pub_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('todo_id', name='todos_pkey')
    )
    # ### end Alembic commands ###
