language: python
python:
  - "3.6.1"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE postgres PASSWORD '' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "create database tests;" -U postgres
  - python run.py db init
  - python run.py db migrate
  - python run.py db upgrade

# command to run tests
script:
  - nosetests --with-coverage test_app.py
  nosetests --with-coverage test_app.py

after_success:
  - coveralls