language: python
python:
  - "3.6.1"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE test PASSWORD '' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "create database tests;" -U postgres

# command to run tests
script:
  - nosetests --with-coverage test_app.py

after_success:
  - coveralls