language: python
python:
  - "3.6.1"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE ROLE test PASSWORD '' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
  - psql -c "create database tests;" -U postgres

# command to run tests
script:
  - nosetests --with-coverage app/tests/

after_success:
  - coveralls

env:
  - db='tests' USER='postgres' PASSWORD='1234' HOST='localhost' PORT=5432 SECRET_KEY='this-is-my--secret--key' SQLALCHEMY_DATABASE_URI2='postgresql://postgres:1234@localhost:5432/tests' SQLALCHEMY_DATABASE_URI='postgresql://postgres:1234@localhost:5432/shopping_list'